services:
  app:
    build: .
    container_name: song-rest-api
    ports:
      - "8080"
    environment:
      - HTTP_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - SSL_MODE=disable
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_postgres:
